language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
  - COMPOSER_FLAGS="--prefer-stable"

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer require phpunit/phpunit --dev --no-update $COMPOSER_FLAGS
  - composer update $COMPOSER_FLAGS
  - mkdir -p build/logs

script:
  - php -dxdebug.mode=coverage vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
